version: "3.4"

services:

  rembg:
    build: .
    init: true
    volumes: 
      - ./input:/tmp/input
      - ./output:/tmp/output
    deploy: {resources: {reservations: {devices: [{driver: nvidia, capabilities: [gpu, video]}]}}}
    command: [
      "p", 
      "-a", # Apply an alpha matting
      "-m", "u2netp", # Model
      "/tmp/input", "/tmp/output",
    ]

    # The available models are:
    # - u2net (download, source): A pre-trained model for general use cases.
    # - u2netp (download, source): A lightweight version of u2net model.
    # - u2net_human_seg (download, source): A pre-trained model for human segmentation.
    # - u2net_cloth_seg (download, source): A pre-trained model for Cloths Parsing from human portrait. Here clothes are parsed into 3 category: Upper body, Lower body and Full body.
    # - silueta (download, source): Same as u2net but the size is reduced to 43Mb.
    # - isnet-general-use (download, source): A new pre-trained model for general use cases.
    # - isnet-anime (download, source): A high-accuracy segmentation for anime character.
    # - sam (download encoder, download decoder, source): A pre-trained model for any use cases.


  # To use this, clone https://github.com/nadermx/backgroundremover at the same
  # level as this project.
  # NOTE: This is not yet working.
  backgroundremover:
    build: ./backgroundremover
    volumes: 
      - ./backgroundremover/input:/input
      - ./backgroundremover/output:/output
    init: true
    deploy: {resources: {reservations: {devices: [{driver: nvidia, capabilities: [gpu, video]}]}}}
    command: -i /input/input.png output.png

